apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-webapp
  name: gitops-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-webapp
  template:
    metadata:
      labels:
        app: gitops-webapp
    spec:
      containers:
      - image: uuvtqd/gitops-webapp:6afd5893dfe2d989cc9575d3862f4c9cdb76fdcd
        name: gitops-webapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: APP_PORT
          value: "5000"
