apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
namespace: demo-dev
images:
- name: gitops-webapp
  newName: uuvtqd/gitops-webapp
  newTag: 3623a04d0bd5c86c6c0ea63c05700f3d95764c5d
- name: uuvtqd/gitops-webapp
  newTag: 1d0a3ef201d6d996f16b5fb30ea4d17838da9388

# Not all Resources or fields support strategic merge patches. 
# To support modifying arbitrary fields in arbitrary Resources, 
# Kustomize offers applying JSON patch through patchesJson6902. 
# https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html

patchesJson6902:
- path: modify_port.yaml
  target:
    group: apps
    kind: Deployment
    name: gitops-webapp
    version: v1
